# Generated by Django 5.2 on 2025-08-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Checks", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE
            OR REPLACE FUNCTION calculate_duration() RETURNS trigger AS $$
            BEGIN
                    IF
            NEW.end_time IS NOT NULL THEN
                        NEW.duration := NEW.end_time - NEW.start_time;
            END IF;
            RETURN NEW;
            END;
                $$
            LANGUAGE plpgsql;

            CREATE TRIGGER update_duration
                BEFORE UPDATE
                ON work_sessions
                FOR EACH ROW
                EXECUTE FUNCTION calculate_duration();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS update_duration ON work_sessions;
                DROP FUNCTION IF EXISTS calculate_duration();
                """
        ),
    ]
